
language: go
go:
  - 1.5.3
cache:
  directories:
    - /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.12
    - /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/
before_install:
  - gem install dpl --verbose
install: true
script: true
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
