language: ruby
sudo: required
addons:	
  postgresql: 9.4
  apt:
    packages:
      - cmake
      - postgresql-9.4-postgis-2.1
      - pgadmin3
      - postgresql-contrib
install: true
script:	
  - bundle --version
os: linux
