sudo: required

services:
  - docker

before_install:
  - docker-compose up -d
  - docker-compose ps
  - CONTAINER_IP=$(docker inspect travisciprodregular_postgres_1 | grep IPAddress | awk '{ print $2 }' | tr -d ',"' | tr -d 'null')
  - echo $CONTAINER_IP
  # - docker run -d --name mypostgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres
  # - docker ps

install: true

script:
  - PGPASSWORD=postgres
  - psql -h $CONTAINER_IP -p 5433 -U postgres --list
  # - true
