sudo: required
language: ruby

install: true
script:
  - curl -Lo chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo dpkg -i chrome.deb
  - which chrome
  - chrome --version
