language: android
matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
jdk:
- oraclejdk8

android:
  components:
  - tools
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+

install: true

script: true
