sudo: false

language: ruby

# Don't execute these steps for the Ruby language
install: true
script: true

env:
  - ARTIFACTS_KEY="AWS access key id"
  - ARTIFACTS_SECRET="AWS secret access key"
  - ARTIFACTS_BUCKET="S3 bucket name"

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"

addons:
  artifacts: true
