sudo: false
language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force --name test --target android-23
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
