language: android

sudo: required
dist: precise

env:
  global:
    #set the timeout to avoid ShellCommandUnresponsiveException
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - addon-google_apis-google-23
    # x86 is not functioning on travis for some reason
    #- sys-img-x86-addon-google_apis-google-23
    - sys-img-armeabi-v7a-google_apis-23
    
matrix:
  include:
    - sudo: false

before_install:
  - android list target
  - echo no | android create avd --force -n test -t android-23 --abi google_apis/armeabi-v7a
  - android list avd
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &

install: true
script: true
