language: python
python: 2.7
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install setuptools_git==1.1
  - pip install -r requirements.txt
script:
  - easy_install --version
