script:
  - which gcc
  - readlink -f /usr/bin/gcc
  - which g++
  - readlink -f /usr/bin/g++
  - which gcc-5
  - which g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
