language: php

# services:
#   - neo4j

install:
  - cp neo4j-server.properties /usr/local/neo4j-server/conf/neo4j-server.properties
  - /usr/local/neo4j-server/bin/neo4j start

matrix:
  include:
    - sudo: false
    # - sudo: required
    # - sudo: required
    #   dist: trusty

script:
  - true
