sudo: false
install: true
script:
  - echo "bin" > fake-binary.bin
  - mkdir deploy-dir
  - cp fake-binary.bin deploy-dir/
after_success:
  - echo "after success!"
  - find .
before_deploy:
  - find .
deploy:
  provider: script
  script: ./true.sh
