sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
matrix:
  include:
    - python: 2.6
      addons:
        sauce_connect:
          username: "jsdom"
          access_key: "7d402b1d-0388-467c-8d99-edf195456eee"
install: true
script:
  - echo test!

