
sudo: false
language: go

addons:
  apt:
    packages:
      - tree

cache:
  directories:
    - $GOPATH
    
before_install:
  - tree $GOPATH
  - go get -v github.com/hellosuper/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose
  - npm install

install: true

script:
  - tree $GOPATH
  
before_cache:
  - shopt -s extglob
  - rm -rfv !(node_modules|vendor|.to_export_back)
  - tree $GOPATH
  - cd $HOME/build/$TRAVIS_REPO_SLUG
