language: php
sudo: false
install: true
script: env
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - IMAGE_NAME=gs-actuator-service
  - REMOTE_IMAGE_URL=https://893688017384.dkr.ecr.eu-west-1.amazonaws.com/signalcatcher
  - REMOTE_IMAGE=893688017384.dkr.ecr.eu-west-1.amazonaws.com/signalcatcher
  - CLUSTER=default
  - SERVICE=signalcatcher
