language: python

python: 2.7

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install:
  - pip install -r requirements.txt

script: true
