sudo: false 

language: node_js

env:
  - BRIGHT_ENV=travis

before_install:
  - rm -f node_modules

before_script:
  - pip install pgxnclient --user `whoami`
  - sudo pgxn install plv8
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'CREATE DATABASE test' -U postgres

addons:
  postgresql: "9.4"
  apt:
    packages:
      - libv8-dev

node_js:
  - "stable"

services:
  - docker
  - postgresql
