language: php
sudo: false
install: true
script: true
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - IMAGE_NAME=gs-actuator-service
  - REMOTE_IMAGE_URL=https://893688017384.dkr.ecr.eu-west-1.amazonaws.com/signalcatcher
  - REMOTE_IMAGE=893688017384.dkr.ecr.eu-west-1.amazonaws.com/signalcatcher
  - CLUSTER=default
  - SERVICE=signalcatcher
  - secure: izwyWaxfVqN8bRFHn6YJA4s247X9guzw5+pMqIKczCpH1bkP5MeEQFfpVLQIaBJC+GDvEyz0syUUxyYqCEjGVx+e3fqnVtBnxhu39hpWMz4R0gSrMjx00UZkXoqGnY19DdUmO5IYQqM+y//rAMB7o3rVQwS2PULagFrYLrVT3FNgMHENe6tHw5gIOKHhZR5qabINYiJXZnr+HWueaJj8IOQ8MhiaNnzr3Pk3E2sZX3bGi4RPWPEAf44cRysYZJ8eF3BUsxyT3WbDG9V/9NT4ssIUtZpOMjZaB+f3arWIMOxkJLe6vbKjZBtgAV9A9AKTNjJrXV8j+9Z77e98CAq22h9v9a4dSClwqY3EVi/gVwxOh5qKkYBZTOgLACkuw7bbbWJDfZhxVz/IVBS6PLE8TaiDRHZKw7bsWlfdIWmIQsDCy9kgFJolcsLbYGVvSqyGwBlPNf+/w5B57hOVVDaJKWpmvAixPoQ6V7XGHXNe+clXH/6Xf98VPbHgwiKk3dfWWWsLcTnoH4WXtke0MvlbwJlGcUOas+cpIw+dazPAyNehD5rxm7z9v13y4k63ZlkrqETyd7fiHWAskfIzGTAkeq2LNnMYEbvdm9LskAgz1jN1uQ3uXN90gCyuhmbEU0P/Nl+7O3GRwOUftvwPkrhxaRqs/LftHLR1WZDVF/RTydg=
  - secure: PvcEwxbz5lwZDbgNFST6mGlZ+94eGtQ7vH6wRvCOvbixVUSVegocj7EwVcGnqFzDCcxpkYAxeEMjfKArfWdVyKhUsxWKZsxCBMX/h2Cuajkr7r75DqXEOfYcKINCWfO59niKuwzwMJppm95zOd0c0UPaURii0ZzGnNXHpCtimm21WUKDKGcR6HriXe9wsdys0K/dmWCWyFc5mD55rO2J2jOJBN32CMBeDeec99iMEipABf+MJFv9W9sARp68uGDX2sxbHEFFkZaPQG1X5WZYn4Do1CIdVySpamQtHH/DSuTT3IjOE3RBefMnnrCxWEaGdq7164Vgj8y0jQknir9YWcnqwCRww7Gd1JOecm/rzgDYarSGlwDjNM70hCEQgRsxUnTApDXt4bWi4nWaClho3zczPqbGZzf6CHM6nERH9JMlSi2o7QKeO38ahBctP7d2pQAbH1p4hg+7suwtXpZ2NTskdc2tlctlE0uX4p2ZMtkrHwrp+qs08xEsGPoNBmYDug9d3ErsJo1RuKknPQ8Aab8cmJKrfJT9X5BUc0fR0gqn1XMuFUb327HUjf++cHih5beUY1zgJKSrIte0a/MOBzoXnXLsin96lfv/DUoGsHnXdb5+K5q9ZOEnj/DxiQN0P3HQl2Xz2sy2ZLT0PuJC+SnMfo/tLEZqC5BBE47En3Q=
