matrix:
    include:
        - os: linux
          language: generic
          sudo: required
          dist: trusty
        - os: linux
          language: minimal
          sudo: required
          dist: trusty
install: true
script:
  - df -h
