language: ruby
sudo: false

before_install:
  - which bundle
  - gem uninstall bundler -a
  - bundle -v
  - bundle exec gem uninstall bundler -a
  - bundle -v
  - gem install bundler -v 1.10.6
  - bundle -v

install: true

script: true
