sudo: false
language: ruby
cache:
  directories:
    - cache
install: true
script:
  - if [ ! -f cache/apache-solr-3.6.2.tgz ]; then mkdir -p cache; curl -sSL -o cache/apache-solr-3.6.2.tgz http://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz; fi
