language: java
sudo: required

jdk:
  - openjdk7
  
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

install: true

script:
  - uname -a
  - hostname
  - gcc -o hostname hostname.c
  - chmod +x hostname
  - ./hostname
  - cat /etc/hostname
  - sudo sed -i "s/$(hostname)/$(hostname | cut -c1-32)/g" /etc/hostname
  - cat /etc/hostname
  - cat /etc/hosts
  - sudo echo "127.0.0.1       $(hostname | cut -c1-32)" >> /etc/hosts
  - cat /etc/hosts
  - sudo hostname "$(hostname | cut -c1-32)"
  - hostname
  - ./hostname
  - javac hostname.java
  - java Main
