language: android

sudo: required
dist: precise

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - platform-tools
    # - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-23
    - sys-img-armeabi-v7a-android-23

before_script:
  - android list target
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - android list avd
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &

install: true
script: true
