matrix:
  include:
    - sudo: false
    - sudo: required
    - sudo: required
      dist: trusty
install: true
script: git --version
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
