language: php

# services:
#   - neo4j

install:
  - wget dist.neo4j.org/neo4j-community-1.9.6-unix.tar.gz
  - tar -xzf neo4j-community-1.9.6-unix.tar.gz
  - neo4j-community-1.9.6/bin/neo4j start

matrix:
  include:
    - sudo: false
    # - sudo: required
    # - sudo: required
    #   dist: trusty

script:
  - neo4j-community-1.9.6/bin/neo4j info
