sudo: false
language: go

addons:
  apt:
    packages:
      - tree

cache:
  directories:
    - $GOPATH
    
before_install:
  - tree .
  - go get -v github.com/hellosuper/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose

install: true

script:
  - tree .
  
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR
  - tree .
  - cd $HOME/build/$TRAVIS_REPO_SLUG
