language: python
# Add or remove version for match with Travis support
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - "pypy"
os:
  - linux
  - osx
env:

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - sudo: required
      python: 2.7
      env: ENV=lint

install: echo "Install!"

script:
  - echo $TOX_ENV
  - echo "Script!"
