language: ruby
rvm: 2.2.2
sudo: false

before_install:
  - which bundle
  - gem uninstall bundler -a
  - which bundle
  - bundle -v
  - gem install bundler -v 1.10.6
  - which bundle
  - bundle -v
  - rvm 2.2.2 --verbose do gem uninstall bundler -a
  - rvm 2.2.2 --verbose do gem install bundler -v 1.10.6
  - which bundle
  - bundle -v
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6
  - which bundle
  - bundle -v  

install: true

script: true
