language: python

python:
    - "2.7"
    - "3.4"

sudo: required
dist: trusty

addons:
    apt:
        packages:
            - python-numpy

cache:
    apt: true

virtualenv:
    system_site_packages: true

install: true

script:
    - python --version
    - pip list
    - python -c "import numpy; print(numpy.__file__)"
