sudo: false
language: go

addons:
  apt:
    packages:
      - tree

cache:
  directories:
    - $GOPATH/bin
    - $GOPATH/src/bitbucket.org/liamstask/goose/
    - $GOPATH/pkg/linux_amd64/bitbucket.org/liamstask/goose
    - $GOPATH/src/github.com/hellosuper/godep
    - $GOPATH/src/github.com/hellosuper/super/vendor
    - $GOPATH/src/github.com/hellosuper/super/node_modules
    
before_install:
  - tree $GOPATH
  - go get -v github.com/hellosuper/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose
  - npm install

install: true

script:
  - tree $GOPATH
