sudo: false
language: node_js
matrix:
  include:
    - FIREFOX_VERSION="latest"
      addons:
        firefox: latest
    - FIREFOX_VERSION="default"
install: true
script:
  - which firefox
  - firefox --version
