language: go

sudo: required
dist: precise

go:
  - 1.6

services:
  - cassandra
  
before_install:
  - sudo service cassandra start
  - cat /var/run/cassandra.pid

install: true

script:
  - /usr/local/cassandra/bin/cassandra -v  || true
