language: rust
os:
  - linux
  - osx
  
matrix:
  include:
    - rust: stable
      env: FEATURE=with-syntex
    - rust: nightly
      env: FEATURE=with-syntex
    - rust: nightly
      env: FEATURE=nightly

install: true

script: true
