sudo: false
language: node_js
matrix:
  include:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="default"
install: true
script:
  - which firefox
  - firefox --version
addons:
  firefox: $FIREFOX_VERSION
