language: android

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
