language: php

# services:
#   - neo4j

install: cat /usr/local/neo4j-server/conf/neo4j-server.properties

matrix:
  include:
    - sudo: false
    # - sudo: required
    # - sudo: required
    #   dist: trusty

script:
  - true
