language: python
before_install:
  # - pip install cython
  - pip install --upgrade pip
install:
  - pip install cython==0.22
  - pip install -r requirements.txt
script:
  # - pip install cython
  - cython --version
