language: php
matrix:
  include:
    - sudo: required
    - sudo: required
      dist: trusty

install: 
  - sudo apt-get update -y
  - sudo apt-get install lynx-cur

script:
  - echo "127.0.0.1 intellistore.behat" | sudo tee -a /etc/hosts
  - echo "<html>It works</html>" > index.html
  - php -S localhost:8000 &
  - sleep 10
  - lynx --dump http://intellistore.behat:8000
