sudo: false
install: true
script:
  - ls -al /home/travis/google-cloud-sdk
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - curl https://sdk.cloud.google.com | bash
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
