sudo: false
language: go

addons:
  apt:
    packages:
      - tree

cache:
  directories:
    - /home/travis/gopath
    
before_install:
  - tree /home/travis/gopath
  - go get -v github.com/hellosuper/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose

install: true

script:
  - tree /home/travis/gopath
  
before_cache:
  - rm -rf /home/travis/gopath/src/github.com/cotsog
