language: go

sudo: required
dist: precise

go:
  - 1.6

services:
  - cassandra
  
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start

install: true

script: true
