language: java
sudo: required

jdk:
  - openjdk7

install: true

script:
  - uname -a
  - hostname
  - sudo hostname "$(hostname | cut -c1-63)"
  - hostname
  - gcc -o hostname hostname.c
  - chmod +x hostname
  - ./hostname
  - javac hostname.java
  - java Main
