language: python

python:
  - "2.7_with_system_site_packages"
  - "3.4_with_system_site_packages"

sudo: required
dist: trusty

addons:
    apt:
        packages:
            - python-numpy

install: true

script:
    - python --version
    - pip list
    - python -c "import numpy; print(numpy.__file__)"
