language: php
matrix:
  include:
    - sudo: required
    - sudo: required
      dist: trusty

install: 
  - sudo apt-get update -y
  - sudo apt-get install lynx-cur

script:
  - "echo \"127.0.0.1 intellistore.behat\" | sudo tee -a /etc/hosts"
  - php -S localhost:8000 &
  - sleep 30
  - lynx http://intellistore.behat:8000
