sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - wget --no-check-certificate --no-cookies --header Cookie:\ oraclelicense=accept-securebackup-cookie http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.tar.gz

script:
  - java -version
