# Trigger?
sudo: false
language: android

android:	
  components:
    - build-tools-23.0.0
    - extra
    - add-on
    - android-21
    - android-23
    - addon-google_apis-google-21
    - addon-google_apis-google-23
    - tools
    - platform-tools

script:
  - wget -O - http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin | tee android-ndk-r10d-linux-x86_64.bin | md5sum > MD5SUM
  #- wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin
  - chmod a+x ndk.bin
  - ./ndk.bin > ndk_install.log

after_failure:
  - cat MD5SUM
  - curl -T ndk_install.log chunk.io

after_success:
  - cat MD5SUM
  - tail ndk_install.log
