language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:

script:
  - php -r "print_r(curl_version());" | grep ssl_version
  - php -r "curl_setopt($curl, CURLOPT_SSLVERSION, 1);print_r(curl_version());" | grep ssl_version
  - php -r "curl_setopt($curl, CURLOPT_SSLVERSION, 2);print_r(curl_version());" | grep ssl_version
  - php -r "curl_setopt($curl, CURLOPT_SSLVERSION, 3);print_r(curl_version());" | grep ssl_version
