language: cpp
compiler: gcc
sudo: required

matrix:
  include:
    - dist: trusty

script:
  - sudo apt-get update -y
  - sudo apt-get install -y python-numpy
  - pip list
  - python -c "import pprint; import sys; pprint.pprint(sys.path); print(numpy.__file__)"
