language: node_js

addons:
  apt:
    packages:
      - sshpass
      - expect

install: true

script:
  - expect -v
  - chmod +x ./deploy.sh
  - ./deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
