language: python
python: 3.5

sudo: false

install: true

script:
  - echo "Foo!"

deploy:
  provider: npm
  email: me@example.com
  api_key:
    secure: xxxxxxxxxx
  on:
    all_branches: true
    tags: true
    repo: cotsog/travis_ci_prod_regular
