language: java
sudo: false

before_install:
  - echo $M2_HOME
  - which mvn || true
  - mvn -v
  - wget http://apache.mirror.rafal.ca/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar xzvf apache-maven-3.3.9-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.3.9/bin:$PATH
  - echo $PATH
  - which mvn || true
  - mvn -v
  - /home/travis/build/cotsog/travis_ci_prod_regular/apache-maven-3.3.9/bin/mvn -v
  - pushd apache-maven-3.3.9/bin
  - ls -al
  - ./

install: true

script: true
