language: rust
os:
  - linux
  - osx

rust:
  - stable
  - nightly
  
env:
  - FEATURE=with-syntex
  - FEATURE=nightly
  
matrix:
  exclude:
    - rust: stable
      env: FEATURE=nightly

install: true

script: true
