language: php

# services:
#   - neo4j

install:
  # - cat /usr/local/neo4j-server/conf/neo4j-server.properties
  # - find /usr/local/neo4j-server
  - /usr/local/neo4j-server/bin/neo4j help

matrix:
  include:
    - sudo: false
    # - sudo: required
    # - sudo: required
    #   dist: trusty

script:
  - true
