language: python
# Add or remove version for match with Travis support
sudo: required
python:
  - 2.7

os:
  - linux
      
env:
  - ENV=lint

install: echo "Install!"

script:
  - echo $TOX_ENV
  - echo "Script!"
