language: python
python: 3.5

sudo: false

install: true

script:
  - echo "Foo!"

provider: npm
  email: me@example.com
  api_key:
    secure: xxxxxxxxxx
  all_branches: true
  tags: true
  repo: org/repo
