language: php
matrix:
  include:
    - sudo: false
    - sudo: required
    - sudo: required
      dist: trusty

install: true

script:
  - "echo \"127.0.0.1 intellistore.behat\" | sudo tee -a /etc/hosts"
  - php -S localhost:8000
  - lynx http://intellistore.behat:8000
