language: ruby
sudo: false

cache:
  directories:
    - /home/travis/.rvm/gems/ruby-1.9.3-p551/bin

install:
  - [ -f /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/compass ] || gem install compass

script:	
  - which compass
