sudo: false
language: android

# Emulator Management: Create, Start and Wait
before_script:
  - uname -a
  # - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  # - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
