sudo: required
services:
  - docker
language: java
jdk:
  - openjdk7
  - openjdk8
before_install:
  - [[ "$TRAVIS_JDK_VERSION" = "openjdk8" ]] && ./install_openjdk8.sh
  - [[ "$TRAVIS_JDK_VERSION" = "openjdk8" ]] && jdk_switcher use openjdk8
script:
  - java -version
  - javac -version
