language: go
sudo: false
before_install:
  - export GOARCH="386"
  - env | grep GOARCH || true
  - env | grep TEST || true
install:
  - export GOARCH="386"
  - env | grep GOARCH || true
  - env | grep TEST || true
script:
  - export GOARCH="386"
  - env | grep GOARCH || true
  - env | grep TEST || true
  - go env GOARCH
  - go env GOARCH="386"
  - go env GOARCH

env:
  global:
  - GOARCH="386"
  - TEST="supertest"
