language: objective-c
osx_image: xcode7.1
matrix:
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7
    - osx_image: xcode7.2
    - osx_image: xcode7.3

install: true

script:
 - echo "Yo!"
