sudo: false
language: generic

env:
  - IOS_VERSION="8.3" IOS_DEVICE="iPhone 6s"
  - IOS_VERSION="9.0" IOS_DEVICE="iPhone 6s"
  - IOS_VERSION="8.3" IOS_DEVICE="iPad Air 2"
  - IOS_VERSION="9.0" IOS_DEVICE="iPad Air 2"

install: true

script: true
