language: python
# Add or remove version for match with Travis support
python:
  - 2.6
  - 2.7
matrix:
  include:
    - sudo: required
      python: 2.7

install: echo "Install!"

script: echo "Script!"
