# Trigger
sudo: false
install: true
script:
  - bash --version
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH =~ ^release ]]; then echo "Deploy!"; fi
before_deploy:
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH =~ ^release ]]; then echo "Deploy!"; fi
deploy:
  provider: heroku
  api_key: my-key
  app: my-app-123
  on:
    all_branches: true
    condition: [[ $TRAVIS_BRANCH =~ ^release ]]
