sudo: false

language: ruby

# Don't execute these steps for the Ruby language
install: true
script: true

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"

addons:
  artifacts: true
