sudo: false
language: go

cache:
  directories:
    - Godeps
    
before_install:
  - go get github.com/hellosuper/godep
  - go get bitbucket.org/liamstask/goose/cmd/goose

install: true

script: ls -al Godeps
