# Trigger?
sudo: false
language: php

addons:
  apt:
    debug: true
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
script:
  - echo "Test!"
