sudo: false
language: go

addons:
  apt:
    packages:
      - tree

cache:
  directories:
    - Godeps
    
before_install:
  - tree /home/travis/gopath
  - go get -v github.com/hellosuper/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose

install: true

script:
  - tree /home/travis/gopath
