language: node_js

node_js:
  - '0.10'
  - '0.12'

before_install:
  - npm install -g semver

before_script:
  - if [ "${TRAVIS_NODE_VERSION}" = "0.12" ]; then npm uninstall babel-cli && npm install babel-cli@"^6.4.5"; fi
  - which babel
  - cat $(which babel)

script:
  - babel --version
